- id: golines
  name: golines
  description: A golang formatter that fixes long lines.
  entry: golines . -w
  types: [go]
  language: golang
  pass_filenames: false
  additional_dependencies: ["golang.org/x/tools/cmd/goimports@52eb446eff42346479727c4e9bd706d3a8e4680a"]
